---
- name: Configure App
  hosts: app
  become: true

  roles:
    - app
    - role: jdauphant.nginx
      nginx_sites:
        default:
          - listen 80
          - server_name "reddit"
          - location / {
              proxy_pass http://127.0.0.1:9292;
            }
