---
- name: Install & Start MongoDB
  hosts: all
  become: true
  tasks:
  - name: remove files
    file:  "path={{ item }} state=absent"
    with_items:
      - /var/lib/dpkg/lock-frontend
      - /var/lib/dpkg/lock
  - name: install packages
    apt:
      name: mongodb-server
    notify: start mongodb
  handlers:
  - name: start mongodb
    service:
      name: mongodb
      state: started
      enabled: yes
